### PR TITLE
Upgrade gun to version 0.8.4

### PR DESCRIPTION
**Pull request by jonmalave**

### CODE REVIEW

**Comment by sjones6** [comment]
@jonmalave : Thanks for putting this PR in! 

I'm thinking to update this to `gun: "*"` so that no version is specified at all since vue-gun doesn't really care about the version at all. I believe that if you've specified another version of `gun` in your `package.json`, then npm should resolve to that package (and not duplicate Gun installs with separate versions).

Does that make sense to you?

**Comment by jonmalave** [comment]
Sounds goods, Let's do that! I'll test the update after you do, ignore this PR in that case. 😉

**Comment by sjones6** [comment]
@jonmalave : Just published update to Vue-gun. Once you update, let me know if it's good to go?

**Comment by jonmalave** [comment]
@sjones6 just updated (re-installed on my end)! seems to be working just fine... good call on the ```gun: "*"``` no version specified. Thanks a bunch for updating!

**Comment by sjones6** [comment]
@jonmalave : Great! Thanks for catching the issue! Much appreciated. :)

**Pull request closed without merging**
